# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18ae1acf7336c50aac001696ca43b72b5e37a4c13326252425e78f3f51793b5d097f4cf3cab5e025337eed7d10ae25bdeb5672a9e0d8a9bbb7557c52008e8e62

test:
  secret_key_base: 81742c5dffaa880b5d8d79d8d12167009b5d948e6c881bde5b445e229be26eb2433a176ba0ab5596b2a5a8c8600c88bcb1a6d14495600f90e0191207da841882

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
